import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BrainCircuit, CalendarCheck2, CircleCheckBig, Target, Trophy } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation } from "wouter";

const tones = {
  Inicial: "border-emerald-100 bg-emerald-50 text-emerald-800",
  Intermédio: "border-blue-100 bg-blue-50 text-blue-800",
  Avançado: "border-amber-100 bg-amber-50 text-amber-800",
};

export default function ChallengesPage() {
  const [, setLocation] = useLocation();
  const [discipline, setDiscipline] = useState<"all" | "matematica" | "fisica" | "quimica" | "geometria" | "portugues" | "cultura">("all");
  const challengeInput = useMemo(() => discipline === "all" ? undefined : { disciplineId: discipline }, [discipline]);
  const challenge = trpc.learning.challenges.today.useQuery(challengeInput);
  const data = challenge.data;

  return <DashboardLayout><header className="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="app-kicker">Desafios de preparação</p><h1 className="mt-1 font-display text-4xl text-slate-950">Pratique em níveis. Evolua com propósito.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Cada desafio é uma sessão curta de questões de treino. Comece pelo nível que consolida o seu raciocínio e avance quando se sentir seguro.</p></div><div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700"><CalendarCheck2 className="mr-2 inline h-4 w-4 text-[#0A36A8]" />Meta semanal: {data?.weeklyTarget ?? 5} sessões</div></header>
    {challenge.isLoading ? <div className="h-64 animate-pulse rounded-3xl bg-slate-100" /> : <><section className="mb-5 flex flex-wrap gap-2" aria-label="Escolher disciplina para desafios">{(["all", "matematica", "fisica", "quimica", "geometria", "portugues", "cultura"] as const).map((item) => <button key={item} onClick={() => setDiscipline(item)} className={`rounded-xl px-3 py-2 text-sm font-bold transition-colors ${discipline === item ? "bg-[#0A36A8] text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{item === "all" ? "Todas as disciplinas" : item === "matematica" ? "Matemática" : item === "fisica" ? "Física" : item === "quimica" ? "Química" : item === "geometria" ? "Desenho e Geometria" : item === "portugues" ? "Língua Portuguesa" : "Cultura Geral"}</button>)}</section><section className="mb-6 overflow-hidden rounded-3xl bg-[#0D1C4D] p-6 text-white sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="app-kicker text-[#FFCC5C]">Desafio de hoje · {data?.daily?.discipline || "Preparação"}</p><h2 className="mt-2 max-w-3xl font-display text-2xl leading-tight sm:text-3xl">{data?.daily?.prompt || "Prepare-se com uma questão curta e objectiva."}</h2><p className="mt-3 text-sm font-semibold text-blue-100">{data?.daily?.topic} · nível {data?.daily?.difficulty}</p></div><Button onClick={() => data?.daily && setLocation(`/app/praticar?question=${data.daily.questionId}&daily=1`)} disabled={!data?.daily || data.daily.completed} className="shrink-0 rounded-xl bg-white text-[#0A36A8] hover:bg-blue-50 disabled:bg-white/20 disabled:text-white">{data?.daily?.completed ? <><CircleCheckBig className="mr-1.5 h-4 w-4" />Concluído</> : <>Resolver agora <ArrowRight className="ml-1 h-4 w-4" /></>}</Button></div></section><section className="grid gap-4 md:grid-cols-3">{data?.levels.map((level) => <article key={level.difficulty} className={`rounded-3xl border p-6 ${tones[level.difficulty]}`}><p className="text-xs font-extrabold uppercase tracking-[0.14em]">Nível {level.difficulty}</p><h2 className="mt-3 font-display text-3xl">{level.title}</h2><p className="mt-2 text-sm leading-6 opacity-80">{level.description}</p><p className="mt-5 text-xs font-bold">{level.available} questões disponíveis</p><Button onClick={() => setLocation(`/app/praticar?difficulty=${encodeURIComponent(level.difficulty)}${discipline === "all" ? "" : `&discipline=${discipline}`}`)} className="mt-5 rounded-xl bg-slate-950 text-white hover:bg-slate-800">Aceitar desafio <ArrowRight className="ml-1 h-4 w-4" /></Button></article>)}</section>
      <section className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><article className="rounded-3xl bg-[#0D1C4D] p-7 text-white"><p className="app-kicker text-[#FFCC5C]">Desafio de recuperação</p><h2 className="mt-2 font-display text-3xl">{data?.recovery.title || "Revise antes de acelerar."}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-blue-100">{data?.recovery.description || "Responda novas questões dos tópicos com menor domínio para transformar erros em próximos passos claros."}</p><Button onClick={() => setLocation(data?.recovery.moduleId ? `/app/praticar?module=${data.recovery.moduleId}&errors=1` : "/app/revisao")} className="mt-6 rounded-xl bg-white text-[#0A36A8] hover:bg-blue-50"><BrainCircuit className="mr-1 h-4 w-4" />Fazer recuperação</Button></article>
        <article className="rounded-3xl border border-slate-200 bg-white p-7"><p className="app-kicker text-slate-400">Como ganhar consistência</p><div className="mt-5 space-y-4">{[[Target, "1. Aprenda", "Leia a aula e confirme o conceito com o exemplo."], [Trophy, "2. Desafie-se", "Faça uma sessão curta no nível adequado."], [BrainCircuit, "3. Recupere", "Volte aos erros antes de iniciar outro simulado."]].map(([Icon, title, text]) => <div key={String(title)} className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#E7EDFF] text-[#0A36A8]"><Icon className="h-4 w-4" /></span><div><p className="font-bold text-slate-900">{String(title)}</p><p className="mt-1 text-sm leading-5 text-slate-600">{String(text)}</p></div></div>)}</div></article></section></>}</DashboardLayout>;
}
