import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BookOpen, CalendarDays, CheckCircle2, Clock3, Target, Trophy } from "lucide-react";
import { useLocation } from "wouter";

function MiniStat({ label, value, hint, tone = "blue" }: { label: string; value: string | number; hint: string; tone?: "blue" | "gold" | "green" }) {
  const toneClass = tone === "gold" ? "border-amber-100 bg-[#FFFAEF]" : tone === "green" ? "border-emerald-100 bg-emerald-50" : "border-[#D8E2FF] bg-[#F4F7FF]";
  return <article className={`rounded-2xl border p-5 ${toneClass}`}><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">{label}</p><p className="mt-2 text-3xl font-extrabold tracking-tight text-slate-950">{value}</p><p className="mt-2 text-xs leading-5 text-slate-600">{hint}</p></article>;
}

export default function StudentDashboardPlus() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const dashboard = trpc.learning.dashboard.useQuery();
  const data = dashboard.data;
  const daily = data?.daily;
  const dailyTarget = daily?.targetMinutes ?? 45;
  const targetPercent = daily?.targetPercent ?? 0;

  return <DashboardLayout>
    {dashboard.isLoading ? <div className="space-y-6"><div className="h-36 animate-pulse rounded-3xl bg-slate-200" /><div className="grid gap-4 md:grid-cols-3"><div className="h-32 animate-pulse rounded-2xl bg-slate-200" /><div className="h-32 animate-pulse rounded-2xl bg-slate-200" /><div className="h-32 animate-pulse rounded-2xl bg-slate-200" /></div></div> : <>
      <header className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="app-kicker">Visão geral</p><h1 className="mt-1 font-display text-3xl tracking-tight text-slate-950 sm:text-4xl">Olá, {data?.profile?.displayName || user?.name?.split(" ")[0] || "estudante"}.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Veja o que já realizou hoje e escolha o próximo passo do seu percurso de preparação.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => setLocation(data?.next ? `/app/aula/${data.next.moduleId}` : "/app/estudar")} className="rounded-xl bg-[#0A36A8] text-white hover:bg-[#092e90]"><BookOpen className="mr-1.5 h-4 w-4" />Continuar percurso</Button><Button variant="outline" onClick={() => setLocation("/app/progresso")} className="rounded-xl border-[#BFD0FF] text-[#0A36A8]">Ver progresso</Button></div></header>

      <section className="overflow-hidden rounded-3xl bg-[#0D1C4D] p-6 text-white shadow-[0_22px_55px_rgba(13,28,77,0.18)] sm:p-8"><div className="grid gap-7 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="app-kicker text-[#FFCC5C]">O seu dia de estudo</p><h2 className="mt-2 font-display text-3xl">Estude com um objetivo visível.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-blue-100">As estatísticas são calculadas a partir das questões e simulados que realmente ficaram registados hoje.</p><div className="mt-6 h-3 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#FFCC5C] transition-[width] duration-300" style={{ width: `${targetPercent}%` }} /></div><div className="mt-3 flex items-center justify-between text-sm"><span className="font-bold">{daily?.minutes ?? 0} de {dailyTarget} min</span><span className="text-blue-100">{targetPercent}% da meta diária</span></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-2xl bg-white/10 p-4"><Clock3 className="h-4 w-4 text-[#FFCC5C]" /><p className="mt-3 text-2xl font-extrabold">{daily?.minutes ?? 0}m</p><p className="mt-1 text-xs text-blue-100">Tempo de estudo</p></div><div className="rounded-2xl bg-white/10 p-4"><Target className="h-4 w-4 text-[#FFCC5C]" /><p className="mt-3 text-2xl font-extrabold">{daily?.questions ?? 0}</p><p className="mt-1 text-xs text-blue-100">Questões hoje</p></div><div className="rounded-2xl bg-white/10 p-4"><Trophy className="h-4 w-4 text-[#FFCC5C]" /><p className="mt-3 text-2xl font-extrabold">{daily?.accuracy ?? 0}%</p><p className="mt-1 text-xs text-blue-100">Acerto diário</p></div><div className="rounded-2xl bg-white/10 p-4"><CalendarDays className="h-4 w-4 text-[#FFCC5C]" /><p className="mt-3 text-2xl font-extrabold">{data?.stats.streak ?? 0}</p><p className="mt-1 text-xs text-blue-100">Dias em sequência</p></div></div></div></section>

      <section className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MiniStat label="Preparação" value={`${data?.stats.preparationIndex ?? 0}%`} hint="Média actual do domínio por módulo." /><MiniStat label="Questões" value={data?.stats.answered ?? 0} hint="Respostas persistidas no seu percurso." tone="green" /><MiniStat label="Acerto geral" value={`${data?.stats.accuracy ?? 0}%`} hint="Resultado acumulado nas questões." tone="gold" /><MiniStat label="Módulos" value={`${data?.stats.completed ?? 0}/${data?.stats.totalModules ?? 0}`} hint="Aulas concluídas." /></section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[1.3fr_0.7fr]"><article className="rounded-3xl border border-slate-200 bg-white p-6"><p className="app-kicker text-[#0A36A8]">Próximo passo recomendado</p><h2 className="mt-2 font-display text-3xl text-slate-950">{data?.next?.title || "Escolha o seu primeiro módulo"}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600">{data?.next?.reason || "Abra o programa oficial para começar uma preparação guiada."}</p><div className="mt-5 flex items-center gap-4"><div className="min-w-0 flex-1"><div className="mb-2 flex justify-between text-xs font-bold text-slate-500"><span>Domínio actual</span><span>{data?.next?.mastery ?? 0}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#0A36A8]" style={{ width: `${data?.next?.mastery ?? 0}%` }} /></div></div><Button onClick={() => setLocation(data?.next ? `/app/aula/${data.next.moduleId}` : "/app/estudar")} className="rounded-xl">Estudar <ArrowRight className="ml-1 h-4 w-4" /></Button></div></article><article className="rounded-3xl border border-slate-200 bg-white p-6"><p className="app-kicker text-slate-400">Consistência</p><h2 className="mt-2 font-display text-2xl text-slate-950">Ação curta, efeito composto.</h2><p className="mt-3 text-sm leading-6 text-slate-600">{daily?.questions ? `Hoje já respondeu ${daily.questions} questão${daily.questions === 1 ? "" : "ões"}. Continue com uma revisão ou um simulado curto.` : "Ainda não há atividade registada hoje. Uma questão de treino já inicia o seu acompanhamento diário."}</p><Button variant="outline" onClick={() => setLocation("/app/praticar")} className="mt-5 rounded-xl border-[#BFD0FF] text-[#0A36A8]"><CheckCircle2 className="mr-1.5 h-4 w-4" />Praticar agora</Button></article></section>
    </>}
  </DashboardLayout>;
}
