import DashboardLayout from "@/components/DashboardLayout";
import { BadgeCheck, ExternalLink, MapPin, Satellite, Wifi } from "lucide-react";

const events = [
  { year: "Projectos contínuos", title: "Inclusão e literacia digital", text: "Angola Online, Andando Com as TIC/Centros Móveis e o Programa Cidadão Digital são referências de revisão para associar acesso, formação e inclusão digital.", icon: Wifi, source: "MINTTICS — Projectos Estruturantes", url: "https://minttics.gov.ao/ao/" },
  { year: "16 dez. 2025", title: "CONTECTA ANGOLA comercial", text: "O lançamento em Luanda foi apresentado no âmbito da exploração das capacidades do ANGOSAT-2 para ampliar conectividade e apoiar zonas remotas e empreendedorismo em TIC.", icon: Satellite, source: "INACOM — CONECTA ANGOLA", url: "https://inacom.gov.ao/2025/12/17/minttics-disponibiliza-a-versao-comercial-do-conecta-angola-2/" },
  { year: "31 dez. 2025", title: "Indicadores de acesso", text: "O Observatório TIC publicou 18,1 milhões de acessos à internet fixa e móvel; use sempre a data da atualização ao responder questões com indicadores.", icon: BadgeCheck, source: "Observatório TIC do INACOM", url: "https://www.observatoriotic.gov.ao/" },
  { year: "11–13 jun. 2026", title: "ANGOTIC 2026 em Talatona", text: "O Angola ICT Forum 2026 foi anunciado para o Centro de Convenções de Talatona, em Luanda, sob o lema “Na rota da transformação digital”.", icon: MapPin, source: "INACOM — ANGOTIC 2026", url: "https://inacom.gov.ao/2025/12/08/realizar-um-angotic-2026-de-referencia-global/" },
];

export default function TicTimelinePage() {
  return <DashboardLayout><main className="mx-auto max-w-5xl"><p className="app-kicker text-[#087765]">Cultura Geral · TIC em Angola</p><h1 className="mt-2 font-display text-4xl text-slate-950">Linha do tempo: conectividade, projectos e eventos.</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">Utilize esta sequência como apoio complementar ao tema oficial. Os itens abaixo derivam de fontes institucionais e as questões associadas são sempre identificadas como questões de treino.</p><section className="mt-8 space-y-4 border-l-2 border-[#BFE7DC] pl-6 sm:pl-10">{events.map((event) => { const Icon = event.icon; return <article key={event.title} className="relative rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><span className="absolute -left-[2.3rem] top-6 grid h-7 w-7 place-items-center rounded-full border-4 border-[#F4FAF8] bg-[#087765] text-white sm:-left-[3rem]"><Icon className="h-3.5 w-3.5" /></span><p className="app-kicker text-[#087765]">{event.year}</p><h2 className="mt-2 font-display text-2xl text-slate-950">{event.title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{event.text}</p><a href={event.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center text-xs font-bold text-[#0A36A8] hover:underline">{event.source}<ExternalLink className="ml-1 h-3.5 w-3.5" /></a></article>;})}</section><p className="mt-8 rounded-2xl bg-[#EAF8F4] p-4 text-sm leading-6 text-[#075E51]">Dica de estudo: pergunte sempre “qual instituição?”, “qual projecto?”, “em que local?” e “qual a data da fonte?” antes de memorizar um facto.</p></main></DashboardLayout>;
}
