export type ModuleTeachingMaterial = {
  objective: string;
  explanation: string;
  steps: string[];
  example: string;
  checkpoint: string;
  answer: string;
  commonError: string;
  examTip: string;
  formula?: string;
  formulaLatex?: string;
};

export const MODULE_TEACHING_MATERIAL: Record<string, ModuleTeachingMaterial> = {
  "mat-geometria-espacial": { objective: "Representar relações espaciais e justificar posições entre rectas, planos e sólidos.", explanation: "A geometria espacial exige alternar entre o desenho, a descrição e a propriedade geométrica. Antes de calcular, identifique o sólido ou a posição relativa e escolha a vista que revela a relação pedida.", steps: ["Faça um esboço com os elementos nomeados.", "Indique rectas, planos e pontos relevantes.", "Classifique paralelismo, perpendicularidade ou intersecção.", "Use a projecção ortogonal para confirmar a relação."], example: "Num cubo, duas arestas que partem do mesmo vértice e pertencem a faces adjacentes são perpendiculares; marque-as na figura antes de responder.", checkpoint: "Que elementos espaciais devem ser identificados antes de decidir uma posição relativa?", answer: "Os pontos, rectas e planos envolvidos, além da vista ou projecção que permite observar a relação.", commonError: "Concluir paralelismo apenas porque dois segmentos parecem paralelos no desenho.", examTip: "Use traços auxiliares e escreva a relação geométrica antes da conta." },
  "mat-conjuntos-condicoes": { objective: "Traduzir condições, proposições e operações de conjuntos com rigor lógico.", explanation: "Conjuntos e lógica usam símbolos para descrever condições. A chave é distinguir quem pertence ao conjunto, qual condição é exigida e qual operação une, intersecta ou complementa conjuntos.", steps: ["Defina o universo de referência.", "Traduza a condição em linguagem matemática.", "Identifique se a operação é união, intersecção ou complemento.", "Teste a conclusão com um elemento simples."], example: "Se A representa múltiplos de 2 e B múltiplos de 3, A ∩ B reúne números que satisfazem as duas condições, como 6.", checkpoint: "O que a intersecção A ∩ B exige de cada elemento?", answer: "Que pertença simultaneamente a A e a B.", commonError: "Trocar união por intersecção quando o enunciado usa 'e'.", examTip: "Reescreva 'e', 'ou' e 'não' com os símbolos ∩, ∪ e complemento." },
  "mat-coordenadas-vetores-espaco": { objective: "Usar coordenadas e vectores em R³ para descrever direcção, posição e perpendicularidade.", explanation: "No espaço, um ponto é descrito por três coordenadas e um vector por componentes. Produtos escalares e equações vectoriais tornam visíveis relações de direcção, distância e perpendicularidade.", steps: ["Registe as três componentes com ordem.", "Construa o vector por subtracção de coordenadas.", "Aplique produto escalar quando a questão pedir perpendicularidade.", "Verifique se o resultado respeita a direcção e o sentido."], example: "Para A(1,0,2) e B(4,2,2), o vector AB é (3,2,0); a componente nula mostra que não há variação em z.", checkpoint: "Quando dois vectores são perpendiculares pelo produto escalar?", answer: "Quando o produto escalar entre eles é igual a zero.", commonError: "Subtrair as coordenadas em ordens diferentes sem manter B − A em todas as componentes.", examTip: "Escreva vectores em coluna para evitar trocar x, y e z." },
  "mat-lugares-geometricos": { objective: "Reconhecer conjuntos de pontos definidos por condições de distância no plano e no espaço.", explanation: "Um lugar geométrico não é apenas uma figura desenhada: é o conjunto de todos os pontos que satisfazem uma condição. A mediatriz, a circunferência e a esfera nascem de condições de igualdade de distâncias.", steps: ["Leia a condição de distância com atenção.", "Identifique os pontos ou elementos de referência.", "Associe a condição à figura geométrica correspondente.", "Escreva a equação ou justificação da figura."], example: "Os pontos equidistantes de A e B formam a mediatriz do segmento AB, e não a própria recta AB.", checkpoint: "Qual condição caracteriza uma circunferência de centro C e raio r?", answer: "A distância de qualquer ponto da circunferência a C é igual a r.", commonError: "Confundir circunferência, que é a linha, com círculo, que inclui a região interior.", examTip: "Sublinhe palavras como 'equidistante', 'raio' e 'centro'." },
  "mat-potencias-radicais": { objective: "Simplificar potências e radicais respeitando bases, expoentes e condições de existência.", explanation: "Potências e radicais são duas formas de representar multiplicações repetidas e raízes. As propriedades só podem ser usadas quando as bases e os expoentes foram identificados corretamente.", steps: ["Separe base e expoente.", "Aplique a propriedade apropriada.", "Transforme expoentes racionais em raízes quando ajudar.", "Simplifique sem alterar o domínio da expressão."], example: "16^(3/4) = (⁴√16)³ = 2³ = 8; primeiro calcule a quarta raiz e depois eleve ao cubo.", checkpoint: "Como interpretar a^(m/n)?", answer: "Como a raiz n-ésima de a elevada a m, ou equivalentemente a potência m da raiz n-ésima de a.", commonError: "Distribuir um expoente sobre uma soma, como se (a+b)² fosse a²+b².", examTip: "Confirme sempre se o expoente atua na base inteira ou apenas num termo." },
  "mat-graficos-quadratica": { objective: "Ler e construir gráficos de funções, com destaque para zeros, vértice e concavidade da parábola.", explanation: "O gráfico de uma função quadrática traduz os coeficientes da expressão em forma visual. O sinal de a indica a concavidade; os zeros e o vértice indicam onde a parábola cruza e muda de direção.", steps: ["Identifique a, b e c.", "Determine a concavidade pelo sinal de a.", "Calcule zeros ou discriminante quando necessário.", "Localize o vértice e esboce o eixo de simetria."], example: "Em f(x)=x²−4, a parábola abre para cima e os zeros são −2 e 2, pois x²=4.", checkpoint: "O que o sinal do coeficiente a revela numa parábola?", answer: "Se ela abre para cima quando a é positivo ou para baixo quando a é negativo.", commonError: "Usar a fórmula de Bhaskara sem verificar primeiro se a equação está na forma ax²+bx+c=0.", examTip: "Faça uma tabela curta com a, b, c, vértice e zeros." },
  "mat-estatistica-inducao": { objective: "Distinguir demonstração por indução de análise estatística e calcular medidas de dados com sentido.", explanation: "A indução matemática prova afirmações para todos os números naturais; a estatística descreve e interpreta conjuntos de dados. Em ambos os casos, a sequência lógica importa mais do que decorar uma fórmula.", steps: ["Identifique se a questão é de prova ou de dados.", "Na indução, verifique base e passo indutivo.", "Em dados, organize valores antes de calcular medidas.", "Interprete o resultado no contexto fornecido."], example: "Para provar uma propriedade por indução, confirme n=1 e depois mostre que, se vale para n, também vale para n+1.", checkpoint: "Quais são as duas etapas indispensáveis da indução matemática?", answer: "O caso base e o passo indutivo que liga n a n+1.", commonError: "Apresentar exemplos numéricos como se eles provassem uma afirmação geral.", examTip: "Em estatística, escreva a unidade e diga o que média, mediana ou dispersão revelam." },
  "mat-exp-log-trig": { objective: "Relacionar exponenciais, logaritmos e funções trigonométricas às suas definições e transformações.", explanation: "Exponenciais e logaritmos são operações inversas; trigonometria descreve relações angulares e periódicas. A resolução começa sempre pelas restrições de domínio e pelas identidades que preservam a equivalência.", steps: ["Identifique base, argumento e domínio.", "Escolha a propriedade ou identidade adequada.", "Transforme a expressão por etapas equivalentes.", "Verifique se a solução satisfaz a condição inicial."], example: "Em log₂(8)=x, escreva 2^x=8; como 2³=8, x=3.", checkpoint: "Que condição uma base logarítmica deve cumprir?", answer: "Deve ser positiva e diferente de 1.", commonError: "Aceitar argumento logarítmico nulo ou negativo em números reais.", examTip: "Depois de resolver uma equação, substitua a resposta na expressão original." },
  "fis-energia-trabalho": { objective: "Relacionar força, deslocamento, trabalho e conservação de energia em situações mecânicas.", explanation: "Trabalho mede a transferência de energia produzida por uma força com deslocamento. Em sistemas ideais, a energia mecânica pode conservar-se; quando há atrito, parte da energia transforma-se em outras formas.", steps: ["Desenhe forças e deslocamento.", "Observe o ângulo entre força e deslocamento.", "Calcule trabalho ou energia com unidades SI.", "Compare estado inicial e final do sistema."], example: "Uma força de 10 N na direção do movimento por 3 m realiza W=10×3=30 J.", checkpoint: "Quando o trabalho de uma força é nulo?", answer: "Quando não há deslocamento ou quando a força é perpendicular ao deslocamento.", commonError: "Somar energia cinética e potencial sem definir o referencial de altura.", examTip: "Indique joule, newton e metro em cada grandeza antes de calcular." },
  "fis-gases-termodinamica": { objective: "Interpretar estados de um gás e aplicar as leis termodinâmicas com unidades consistentes.", explanation: "A termodinâmica relaciona pressão, volume, temperatura, calor e trabalho. Em problemas de gases, a temperatura absoluta e o tipo de transformação determinam a relação que pode ser aplicada.", steps: ["Converta temperatura para kelvin.", "Liste pressão, volume e quantidade de matéria.", "Identifique se o processo é isotérmico, isobárico ou isocórico.", "Aplique a equação de estado ou a primeira lei."], example: "Em transformação isotérmica de gás ideal, a temperatura é constante e pV permanece constante.", checkpoint: "Por que a temperatura deve ser convertida para kelvin nas leis dos gases?", answer: "Porque as relações proporcionais usam a escala absoluta de temperatura.", commonError: "Usar graus Celsius diretamente em pV=nRT.", examTip: "Monte uma tabela inicial/final com p, V e T antes de escolher a lei." },
  "fis-corrente-redes": { objective: "Analisar corrente, tensão, resistência e associações de resistores em circuitos.", explanation: "Circuitos elétricos são redes de caminhos para carga elétrica. A Lei de Ohm liga tensão, corrente e resistência; em série e paralelo, a grandeza que se conserva ou se divide muda.", steps: ["Desenhe o circuito e marque polaridades.", "Identifique série ou paralelo.", "Determine a resistência equivalente.", "Use U=RI e confira unidades."], example: "Dois resistores de 2 Ω e 3 Ω em série têm resistência equivalente de 5 Ω.", checkpoint: "O que é igual em todos os elementos ligados em série?", answer: "A corrente elétrica que atravessa cada elemento.", commonError: "Somar resistências em paralelo como se estivessem em série.", examTip: "Comece sempre por reduzir o circuito à resistência equivalente." },
  "fis-cinematica-newton": { objective: "Descrever movimentos e explicar a relação entre forças, massa e aceleração.", explanation: "Cinemática descreve como o movimento acontece; dinâmica explica por que ele muda. As Leis de Newton conectam a resultante das forças à aceleração do corpo.", steps: ["Escolha um referencial e sentido positivo.", "Liste posição, velocidade e aceleração.", "Desenhe o diagrama de forças.", "Aplique a segunda lei à resultante."], example: "Se uma força resultante de 12 N atua numa massa de 3 kg, a aceleração é 4 m/s².", checkpoint: "O que acontece a um corpo se a força resultante é zero?", answer: "Mantém repouso ou movimento retilíneo uniforme, de acordo com a primeira lei de Newton.", commonError: "Confundir velocidade constante com ausência de forças individuais; o que importa é a resultante nula.", examTip: "Desenhe todas as forças antes de escrever F=ma." },
  "fis-oscilacoes-ondas-luz": { objective: "Relacionar período, frequência, comprimento de onda e comportamento da luz.", explanation: "Oscilações repetem-se no tempo; ondas transportam energia por meio de uma perturbação. A frequência indica quantas oscilações ocorrem por segundo e se relaciona ao período.", steps: ["Identifique a grandeza pedida.", "Use f=1/T para frequência e período.", "Relacione v, λ e f quando houver propagação.", "Descreva o fenómeno óptico com o desenho de raios."], example: "Uma onda de frequência 5 Hz tem período T=1/5=0,2 s.", checkpoint: "Como se relacionam frequência e período?", answer: "São inversos: f=1/T.", commonError: "Usar amplitude como se fosse comprimento de onda.", examTip: "Desenhe um ciclo completo e marque crista, vale, λ e amplitude." },
  "fis-dinamica-fluidos": { objective: "Aplicar leis de Newton, gravitação e princípios dos fluidos a situações físicas reais.", explanation: "Em fluidos, pressão e empuxo dependem da profundidade, densidade e volume deslocado. A mecânica usa as mesmas leis de força, mas exige atenção às direções e aos diagramas.", steps: ["Isole o corpo ou porção de fluido.", "Represente peso, normal, tensão ou empuxo.", "Use a relação física compatível com o fenômeno.", "Verifique se o resultado tem direção e unidade coerentes."], example: "Um objeto imerso desloca fluido e recebe empuxo igual ao peso do fluido deslocado, segundo Arquimedes.", checkpoint: "De que grandeza depende o empuxo num fluido?", answer: "Da densidade do fluido, da gravidade e do volume de fluido deslocado.", commonError: "Usar massa do objeto no lugar do volume deslocado ao calcular empuxo.", examTip: "Em questões de fluido, indique acima e abaixo do objeto as forças verticais." },
  "fis-magnetismo-inducao": { objective: "Distinguir campo magnético, força magnética e indução eletromagnética.", explanation: "Magnetismo descreve efeitos de cargas em movimento e correntes; indução ocorre quando a variação de fluxo magnético produz tensão. Sentido e variação são decisivos nas leis de Faraday e Lenz.", steps: ["Identifique fonte do campo e sentido do movimento.", "Use a regra da mão apropriada.", "Verifique se há variação de fluxo.", "Determine o sentido que se opõe à mudança."], example: "Aproximar um íman de uma espira altera o fluxo e pode induzir corrente na espira.", checkpoint: "O que precisa variar para haver indução eletromagnética?", answer: "O fluxo magnético através do circuito.", commonError: "Afirmar que um campo magnético estacionário sempre induz corrente.", examTip: "Desenhe setas para campo, movimento e corrente induzida." },
  "fis-ca-ondas-em": { objective: "Interpretar corrente alternada, transformadores e o espectro eletromagnético.", explanation: "A corrente alternada muda de sentido periodicamente e permite transformação eficiente de tensões. Ondas eletromagnéticas propagam-se no vácuo e diferem por frequência e comprimento de onda.", steps: ["Identifique se a grandeza é eficaz, máxima ou instantânea.", "Analise espiras de primário e secundário em transformadores.", "Localize a onda no espectro.", "Relacione frequência, energia e comprimento de onda."], example: "Num transformador ideal, mais espiras no secundário do que no primário elevam a tensão.", checkpoint: "Qual é a relação entre frequência e comprimento de onda no vácuo?", answer: "São inversamente proporcionais, pois c=λf.", commonError: "Confundir corrente alternada com corrente que apenas diminui de valor.", examTip: "Escreva o que permanece constante no transformador ideal antes de calcular." },
  "qui-equacoes-cinetica-equilibrio": { objective: "Balancear reações e relacionar velocidade, energia de ativação e equilíbrio químico.", explanation: "Uma equação química equilibrada conserva átomos; cinética estuda a rapidez da reação; equilíbrio descreve o estado dinâmico em que reações direta e inversa ocorrem à mesma velocidade.", steps: ["Conte átomos em reagentes e produtos.", "Ajuste coeficientes, não índices.", "Identifique fatores que alteram velocidade.", "Use o princípio de Le Châtelier ao analisar perturbações."], example: "Em N₂+3H₂⇌2NH₃, a pressão favorece o lado com menor número de mols gasosos.", checkpoint: "O que é igual no equilíbrio químico?", answer: "As velocidades das reações direta e inversa, e não necessariamente as concentrações.", commonError: "Alterar fórmulas químicas em vez de apenas coeficientes ao balancear.", examTip: "Marque estados físicos e conte elementos antes de começar o balanceamento." },
  "qui-acidos-bases": { objective: "Classificar ácidos e bases e interpretar pH, neutralização e titulação.", explanation: "Ácidos e bases podem ser descritos pela transferência de protões ou pela presença de íons em solução. O pH é uma escala logarítmica: pequenas mudanças representam variações importantes de concentração.", steps: ["Identifique espécies doadoras e aceitadoras de H⁺.", "Observe se há ácido forte ou fraco.", "Use a escala de pH com cuidado.", "Balanceie a neutralização antes de calcular."], example: "HCl + NaOH → NaCl + H₂O representa uma neutralização entre ácido e base.", checkpoint: "O que ocorre numa neutralização ácido-base simples?", answer: "Íons H⁺ e OH⁻ formam água, gerando sal e água no modelo mais comum.", commonError: "Achar que pH 2 é apenas um pouco mais ácido que pH 3; a escala é logarítmica.", examTip: "Associe sempre o valor de pH à acidez, basicidade ou neutralidade." },
  "qui-atomo-ligacoes": { objective: "Relacionar estrutura eletrónica, tabela periódica e tipos de ligação química.", explanation: "A configuração eletrónica ajuda a explicar reatividade e posições na tabela periódica. Ligações iónicas envolvem transferência predominante de eletrões; covalentes envolvem partilha.", steps: ["Determine número atómico e eletrões de valência.", "Localize grupo e período.", "Compare tendência de perder, ganhar ou partilhar eletrões.", "Represente a ligação por fórmula ou estrutura de Lewis."], example: "Na tende a perder um eletrão e Cl a ganhar um; forma-se Na⁺ e Cl⁻ em ligação iónica.", checkpoint: "Qual informação eletrónica é mais útil para prever ligação?", answer: "O número de eletrões de valência e a tendência de os perder, ganhar ou partilhar.", commonError: "Confundir número atómico com número de massa.", examTip: "Use a tabela periódica para conferir grupo, período e valência." },
  "qui-eletroquimica-coordenacao": { objective: "Distinguir oxidação, redução, pilhas, eletrólise e complexos de coordenação.", explanation: "Reações redox transferem eletrões. Em pilhas, a reação espontânea gera corrente; na eletrólise, uma fonte externa força uma reação não espontânea.", steps: ["Atribua números de oxidação.", "Identifique quem perde e ganha eletrões.", "Localize ânodo e cátodo conforme o sistema.", "Balanceie elétrons antes de concluir a equação."], example: "Zn(s) → Zn²⁺ + 2e⁻ é oxidação porque o zinco perde eletrões.", checkpoint: "Qual espécie sofre redução?", answer: "A espécie que ganha eletrões e diminui o número de oxidação.", commonError: "Trocar ânodo e cátodo por memorizar sinais sem considerar pilha ou eletrólise.", examTip: "Escreva explicitamente 'perde e⁻' ou 'ganha e⁻' em cada semirreação." },
  "qui-carbono-organica": { objective: "Reconhecer cadeias carbónicas, grupos funcionais e relações entre estrutura e propriedades.", explanation: "A química orgânica estuda compostos de carbono e seus grupos funcionais. Nome, fórmula e reatividade dependem da cadeia principal, ligações e substituintes.", steps: ["Identifique a cadeia de carbono.", "Localize ligações simples, duplas ou triplas.", "Reconheça o grupo funcional.", "Relacione a estrutura à classe do composto."], example: "CH₃CH₂OH possui grupo –OH ligado a carbono saturado; é um álcool, etanol.", checkpoint: "Que parte da molécula define muitas propriedades químicas de uma função orgânica?", answer: "O grupo funcional característico.", commonError: "Classificar qualquer composto com oxigénio como álcool sem observar a ligação do grupo funcional.", examTip: "Circule o grupo funcional antes de tentar nomear o composto." },
  "qui-funcoes-reacoes-organicas": { objective: "Diferenciar funções orgânicas e reconhecer reações de adição, substituição, oxidação e esterificação.", explanation: "Cada função orgânica possui um grupo funcional e reatividade própria. As reações mostram como ligações ou grupos são criados, substituídos ou transformados.", steps: ["Identifique o grupo funcional inicial.", "Observe reagentes e condições.", "Verifique qual ligação ou grupo se altera.", "Classifique o tipo de reação e o produto."], example: "Ácido carboxílico + álcool podem formar éster e água numa esterificação.", checkpoint: "Que dois reagentes caracterizam uma esterificação simples?", answer: "Um ácido carboxílico e um álcool.", commonError: "Confundir éster com éter por ambos conterem oxigénio.", examTip: "Desenhe a parte funcional do reagente e do produto lado a lado." },
  "qui-biomoleculas-solucoes": { objective: "Relacionar biomoléculas, forças intermoleculares e propriedades de soluções.", explanation: "Biomoléculas apresentam estruturas ligadas às suas funções; forças intermoleculares explicam estados físicos, solubilidade e ebulição. Em soluções, a presença de soluto altera propriedades do solvente.", steps: ["Identifique o tipo de molécula ou sistema.", "Observe polaridade e possíveis ligações de hidrogénio.", "Relacione interação com propriedade observada.", "Diferencie concentração de propriedade coligativa."], example: "A água tem ponto de ebulição elevado para a sua massa devido às ligações de hidrogénio entre moléculas.", checkpoint: "Que efeito as forças intermoleculares podem ter numa substância?", answer: "Podem alterar pontos de fusão e ebulição, viscosidade e solubilidade.", commonError: "Confundir ligação covalente dentro da molécula com força intermolecular entre moléculas.", examTip: "Ao comparar substâncias, indique primeiro se são polares e quais interações predominam." },
  "geo-projecoes": { objective: "Interpretar projecções ortogonais e axonométricas para representar objetos tridimensionais.", explanation: "A geometria descritiva transforma o espaço em vistas organizadas. Cada projeção conserva algumas informações e exige leitura cuidadosa de alinhamentos, visibilidade e cotas.", steps: ["Identifique planos de projeção e linha de terra.", "Localize a vista frontal, horizontal ou lateral.", "Projete pontos por perpendiculares.", "Confirme correspondência entre as vistas."], example: "Um ponto acima do plano horizontal aparece com cota positiva na projeção frontal.", checkpoint: "Por que uma única vista normalmente não basta para descrever um objeto espacial?", answer: "Porque uma vista pode ocultar profundidade, altura ou posição relativa; várias vistas complementam a informação.", commonError: "Transferir medidas entre vistas sem usar linhas de chamada perpendiculares.", examTip: "Mantenha as linhas de projeção finas e alinhadas." },
  "geo-dupla-projecao": { objective: "Construir e interpretar ponto, recta e plano em dupla projeção ortogonal.", explanation: "Na dupla projeção, os planos horizontal e frontal trabalham juntos para situar objetos no espaço. A leitura de traços, visibilidades e interseções depende da correspondência rigorosa entre projeções.", steps: ["Marque projeção horizontal e frontal.", "Use projetantes perpendiculares à linha de terra.", "Localize traços de rectas e planos.", "Resolva interseções em ambas as vistas."], example: "Uma recta horizontal tem projeção frontal paralela à linha de terra; verifique essa característica antes de classificá-la.", checkpoint: "O que liga a projeção horizontal e a frontal de um mesmo ponto?", answer: "Uma linha projetante perpendicular à linha de terra.", commonError: "Tratar duas projeções como desenhos independentes.", examTip: "Após cada construção, confirme se as projetantes correspondem ao mesmo ponto." },
  "geo-metodos-metricos": { objective: "Usar mudança de planos, rotação e rebatimento para revelar verdadeiras grandezas.", explanation: "Métodos métricos mudam a posição de um plano ou objeto para que uma distância ou ângulo apareça em verdadeira grandeza. O método não altera o objeto; altera a forma de observá-lo.", steps: ["Identifique a grandeza que está deformada.", "Escolha rotação, rebatimento ou mudança de plano.", "Conserve charneira, distâncias e projetantes.", "Leia a verdadeira grandeza na posição auxiliar."], example: "Para ver a verdadeira grandeza de uma figura num plano oblíquo, rebata o plano sobre um plano de projeção.", checkpoint: "Para que serve um rebatimento?", answer: "Para colocar um plano em posição favorável e revelar medidas ou formas em verdadeira grandeza.", commonError: "Mover a charneira durante o rebatimento.", examTip: "Destaque a charneira antes de desenhar arcos de rotação." },
  "geo-formas-solidos": { objective: "Representar figuras e sólidos respeitando o plano de apoio, visibilidade e método de construção.", explanation: "Formas planas e sólidos precisam ser interpretados conforme o plano em que assentam. A construção correta distingue arestas visíveis, ocultas e a relação entre base, altura e planos de projeção.", steps: ["Identifique o plano que contém a figura ou base.", "Construa primeiro elementos determinantes.", "Projete vértices e arestas para as outras vistas.", "Aplique convenções de visibilidade."], example: "Um prisma assente num plano horizontal terá a base em verdadeira grandeza na projeção horizontal quando a base for paralela a esse plano.", checkpoint: "O que determina onde uma figura aparece em verdadeira grandeza?", answer: "O paralelismo entre o plano da figura e o plano de projeção correspondente.", commonError: "Desenhar arestas ocultas com o mesmo traço das visíveis.", examTip: "Separe traço contínuo forte, fino e interrompido conforme a convenção usada." },
  "pt-sintaxe-regencia-discurso": { objective: "Analisar relações sintáticas, regência, vozes verbais e formas de discurso.", explanation: "A sintaxe mostra como palavras e orações se relacionam. Regência exige preposições específicas; discurso direto e indireto mudam a forma de apresentar a fala, mas devem preservar o sentido e os tempos verbais.", steps: ["Localize verbo e complementos.", "Teste a preposição exigida pelo termo regente.", "Classifique as orações pela relação sintática.", "Observe mudanças de pessoa, tempo e pontuação no discurso."], example: "Em 'gosto de leitura', o verbo gostar exige a preposição de; 'gosto a leitura' não respeita a regência.", checkpoint: "O que deve ser observado ao passar discurso direto para indireto?", answer: "Pronomes, tempos verbais, conectores e manutenção do sentido da fala.", commonError: "Classificar uma oração apenas pelo conector, sem verificar a função que exerce.", examTip: "Faça perguntas ao verbo para encontrar complementos e regências." },
  "pt-literatura-angolana": { objective: "Reconhecer recursos expressivos e situar autores angolanos pelo texto e seus temas.", explanation: "Literatura combina linguagem, forma e contexto. Figuras de estilo criam efeitos de sentido; a leitura de autores angolanos deve relacionar voz poética, imagens, temas sociais e escolhas linguísticas.", steps: ["Leia o excerto sem procurar resposta imediata.", "Marque imagens, repetições e contrastes.", "Identifique a figura de estilo e seu efeito.", "Relacione o tema à voz e ao contexto literário."], example: "Uma metáfora aproxima dois elementos sem usar 'como'; 'a cidade acordou' atribui ação humana à cidade, criando personificação.", checkpoint: "Para que serve uma figura de estilo numa leitura literária?", answer: "Para produzir efeito de sentido, intensidade, imagem ou ritmo, e não apenas ornamentar o texto.", commonError: "Nomear uma figura sem explicar o efeito produzido no excerto.", examTip: "Cite uma palavra ou expressão do texto antes de justificar a interpretação." },
};

const DISCIPLINE_ACTION: Record<string, string> = {
  matematica: "escreva as relações simbólicas e verifique cada condição de existência",
  fisica: "desenhe as grandezas, indique unidades SI e relacione causa física e resultado",
  quimica: "identifique espécies, conservação de matéria e transformação química envolvida",
  geometria: "use vistas coerentes, projetantes e convenções gráficas para justificar a construção",
  portugues: "apoie a análise em marcas linguísticas presentes no enunciado ou no texto",
  cultura: "associe o acontecimento à instituição, finalidade e impacto apresentados no material de estudo",
};

export function buildSpecificTopicSession(input: { moduleId: string; moduleTitle: string; disciplineId: string; topic: string; index: number; baseDefinition: string; baseExplanation: string }) {
  const material = MODULE_TEACHING_MATERIAL[input.moduleId];
  const action = DISCIPLINE_ACTION[input.disciplineId] ?? "identifique o conceito, os dados e a relação pedida";
  const definition = input.baseDefinition.includes("É um tópico oficial") ? `No tópico “${input.topic}”, reconheça a ideia central, as condições em que ela se aplica e a representação usada em ${input.moduleTitle}.` : input.baseDefinition;
  const explanation = material ? `${material.explanation} Nesta sessão, aprofunde “${input.topic}”: ${action}.` : `${input.baseExplanation} Para “${input.topic}”, ${action}.`;
  const example = material ? `${material.example} Relacione este procedimento com o tópico “${input.topic}”.` : `Construa uma resolução curta para “${input.topic}”: ${action}.`;
  const checkpoint = material ? `${material.checkpoint} Relacione a resposta diretamente a “${input.topic}”.` : `Que dado, regra ou condição de “${input.topic}” decide o método?`;
  const answer = material ? `${material.answer} No tema “${input.topic}”, explique essa relação antes de calcular ou classificar.` : `A resposta deve indicar o conceito de “${input.topic}”, os dados relevantes e a condição que autoriza o procedimento.`;
  return { topic: input.topic, focus: `Sessão ${input.index + 1}: ${input.topic}`, definition, explanation, example, checkpoint, answer, practiceAction: `Resolva uma questão de “${input.topic}” e, no primeiro passo, ${action}.` };
}

export function buildModuleCheckpointQuestion(input: { moduleId: string; moduleTitle: string; primaryTopic: string; secondaryTopic: string }) {
  const material = MODULE_TEACHING_MATERIAL[input.moduleId];
  const answer = material?.answer ?? `Identifique o conceito de ${input.primaryTopic}, os dados e a condição que permite aplicar o procedimento.`;
  const prompt = material ? `${input.primaryTopic}: ${material.checkpoint}` : `Qual procedimento é decisivo numa questão sobre ${input.primaryTopic}?`;
  const correctOption = Array.from(`${input.moduleId}:${input.primaryTopic}`).reduce((total, character) => total + character.charCodeAt(0), 0) % 4;
  const options = ["Aplicar uma fórmula antes de identificar as condições da questão.", "Ignorar dados, unidades ou relações indicadas no enunciado.", "Escolher uma resposta sem justificar a relação com o tópico."];
  options.splice(correctOption, 0, answer);
  return {
    prompt,
    options,
    correctOption,
    explanation: `${answer} Esta é a ideia que organiza a resolução em ${input.moduleTitle}.`,
    errorHint: `Volte ao material de ${input.moduleTitle} e explique como “${input.primaryTopic}” orienta o primeiro passo.`,
    reviewPrompt: `Verdadeiro ou falso: em ${input.moduleTitle}, o estudo de ${input.primaryTopic} prepara a aplicação consciente de ${input.secondaryTopic}.`,
    reviewExplanation: material ? `Verdadeiro. ${material.explanation}` : `Verdadeiro. Os tópicos são estudados em sequência para relacionar conceito, condição e procedimento.`,
  };
}

export function buildTopicTrainingQuestion(input: { moduleTitle: string; topic: string; definition: string; checkpoint: string; answer: string; practiceAction: string }) {
  const correctOption = Array.from(`${input.moduleTitle}:${input.topic}`).reduce((total, character) => total + character.charCodeAt(0), 0) % 4;
  const options = ["Memorizar uma regra sem verificar se as condições do enunciado permitem usá-la.", "Ignorar os dados específicos e aplicar sempre o mesmo procedimento.", "Escolher uma alternativa pela aparência, sem relacioná-la ao conceito."];
  options.splice(correctOption, 0, input.answer);
  return {
    prompt: `No tópico “${input.topic}”, qual resposta demonstra domínio do que deve ser verificado primeiro? ${input.checkpoint}`,
    options,
    correctOption,
    explanation: `${input.answer} A definição de apoio é: ${input.definition}`,
    errorHint: input.practiceAction,
  };
}
