import { lazy, Suspense, useState } from "react";
import { BookmarkCheck, BookOpenCheck, Download, Loader2, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

type Guide = { id?: number; title: string; explanation: string; workedExample: string; selfCheck: string; answerGuide: string; focus: string; notice: string };
const generatedNotice = "Aprofundamento gerado pelo LUANDA AI a partir do conteúdo curricular do módulo; confirme sempre com a aula e o programa oficial.";
const Streamdown = lazy(() => import("streamdown").then(module => ({ default: module.Streamdown })));

export function LessonExpansion({ moduleId }: { moduleId: string }) {
  const [guide, setGuide] = useState<Guide | null>(null);
  const expand = trpc.ai.lessonExpansion.useMutation({ onSuccess: (value) => setGuide(value) });
  const saved = trpc.ai.savedLessonExpansions.useQuery({ moduleId });
  const save = trpc.ai.saveLessonExpansion.useMutation({ onSuccess: (value) => { setGuide((current) => current ? { ...current, id: value.id } : current); saved.refetch(); } });
  const saveGuide = () => { if (!guide) return; save.mutate({ moduleId, focus: guide.focus, title: guide.title, explanation: guide.explanation, workedExample: guide.workedExample, selfCheck: guide.selfCheck, answerGuide: guide.answerGuide }); };
  return <section className="rounded-2xl border border-[#D8E2FF] bg-gradient-to-br from-[#F5F8FF] to-[#FFFCF2] p-5">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="app-kicker text-[#0A36A8]">Aprofundamento contextual</p><h2 className="mt-1 font-display text-2xl text-slate-950">Construa a explicação com o LUANDA AI.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">Gere uma explicação complementar, um exemplo orientado e uma verificação curta a partir dos tópicos oficiais desta aula.</p></div><Button onClick={() => expand.mutate({ moduleId })} disabled={expand.isPending} className="shrink-0 rounded-xl bg-[#0A36A8] text-white hover:bg-[#082D8A]">{expand.isPending ? <><Loader2 className="mr-2 h-4 w-4 animate-spin" />A preparar…</> : <><Sparkles className="mr-2 h-4 w-4" />Aprofundar aula</>}</Button></div>
    {expand.error && <p role="alert" className="mt-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{expand.error.message}</p>}
    {guide && <div className="mt-5 space-y-4 rounded-2xl border border-white bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-3"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#E7EDFF] text-[#0A36A8]"><BookOpenCheck className="h-5 w-5" /></span><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-[#0A36A8]">{guide.focus}</p><h3 className="font-display text-xl text-slate-950">{guide.title}</h3></div></div><div className="flex flex-wrap gap-2">{guide.id ? <a href={`/api/export/pdf?type=expansion&expansionId=${guide.id}`} className="inline-flex h-9 items-center rounded-xl border border-[#BFD0FF] px-3 text-xs font-bold text-[#0A36A8] hover:bg-[#F3F6FF]"><Download className="mr-1.5 h-4 w-4" />Exportar PDF</a> : <Button onClick={saveGuide} disabled={save.isPending} variant="outline" size="sm" className="rounded-xl border-[#BFD0FF] text-[#0A36A8]">{save.isPending ? <Loader2 className="mr-1.5 h-4 w-4 animate-spin" /> : <BookmarkCheck className="mr-1.5 h-4 w-4" />}{save.isPending ? "A guardar…" : "Guardar"}</Button>}</div></div>{save.error && <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{save.error.message}</p>}<div className="prose prose-slate max-w-none text-sm leading-7"><Suspense fallback={<p className="text-slate-500">A carregar a explicação…</p>}><Streamdown>{guide.explanation}</Streamdown></Suspense></div><div className="grid gap-3 lg:grid-cols-2"><article className="rounded-xl bg-emerald-50 p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-emerald-700">Exemplo orientado</p><p className="mt-2 text-sm leading-6 text-slate-700">{guide.workedExample}</p></article><article className="rounded-xl bg-amber-50 p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-amber-700">Verifique-se</p><p className="mt-2 text-sm leading-6 text-slate-700">{guide.selfCheck}</p><p className="mt-3 border-t border-amber-100 pt-3 text-sm leading-6 text-slate-700"><strong>Guia:</strong> {guide.answerGuide}</p></article></div><p className="text-xs leading-5 text-slate-500">{guide.notice}</p></div>}
    {saved.data?.length ? <div className="mt-5 border-t border-[#D8E2FF] pt-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Aprofundamentos guardados nesta aula</p><div className="mt-3 space-y-2">{saved.data.slice(0, 4).map((item) => <div key={item.id} className="flex flex-col gap-2 rounded-xl border border-slate-100 bg-white px-3 py-3 sm:flex-row sm:items-center sm:justify-between"><button onClick={() => setGuide({ id: item.id, title: item.title, explanation: item.explanation, workedExample: item.workedExample, selfCheck: item.selfCheck, answerGuide: item.answerGuide, focus: item.focus, notice: generatedNotice })} className="min-w-0 text-left"><p className="truncate text-sm font-bold text-slate-800">{item.title}</p><p className="mt-0.5 text-xs text-slate-500">{new Date(item.createdAt).toLocaleDateString("pt-PT")}</p></button><a href={`/api/export/pdf?type=expansion&expansionId=${item.id}`} className="inline-flex items-center text-xs font-bold text-[#0A36A8] hover:underline"><Download className="mr-1 h-3.5 w-3.5" />PDF</a></div>)}</div></div> : null}
  </section>;
}
